import type { Language } from "../LanguageContext";

export type StorySceneTone = "neutral" | "cold" | "rebirth" | "silence" | "return";
export type StoryMediaLayout = "project-left" | "project-right" | "project-wide" | "portrait-right" | "vertical-right";
export type Localized = { en: string; uk: string };
export type StoryMedia = { src:string; alt:Localized; layout:StoryMediaLayout; opacity?:number; objectPosition?:string; parallax?:number };
export type StoryScene = { id:string; label:Localized; title:Localized; description?:Localized; lines?:Localized[]; tone:StorySceneTone; oversizedWord?:Localized; media?:StoryMedia };
export const localize = (value: Localized, language: Language) => value[language];

export const storyScenes: StoryScene[] = [
 { id:"beginning", label:{en:"2005",uk:"2005"}, title:{en:"Born in Kryvyi Rih, Ukraine.",uk:"Народився у Кривому Розі, Україна."}, description:{en:"Before the music, before the name and before the first release, there was simply a kid growing up in an industrial city.",uk:"До музики, до імені й до першого релізу був просто хлопець, який ріс у промисловому місті."}, tone:"neutral", media:{src:"/story/vertical-memory.mp4",alt:{en:"A vertical memory from Evelasting's early creative path",uk:"Спогад із раннього творчого шляху Evelasting"},layout:"vertical-right",opacity:1.28,objectPosition:"center",parallax:10}},
 { id:"first-beat", label:{en:"2022",uk:"2022"}, title:{en:"Everything started with a simple beat.",uk:"Усе почалося з простого біта."}, description:{en:"A friend asked for an instrumental with nothing more than a kick and a bass. It was the first time FL Studio was opened — and the beginning of something that would return again and again.",uk:"Друг попросив інструментал, у якому були лише кік і бас. Тоді FL Studio відкрилася вперше — і почалося те, що поверталося знову й знову."}, tone:"cold", media:{src:"/story/project-sound.png",alt:{en:"An early Evelasting project opened in FL Studio",uk:"Ранній проєкт Evelasting у FL Studio"},layout:"project-left",opacity:.43,objectPosition:"center",parallax:30}},
 { id:"finding-a-sound", label:{en:"Finding a sound",uk:"Пошук звучання"}, title:{en:"Phonk became a way to express what words could not.",uk:"Фонк став способом висловити те, чого не могли передати слова."}, description:{en:"It could feel calm and distant, emotional and melancholic, or aggressive and motivating. The contrast made the genre feel limitless.",uk:"Він міг бути спокійним і віддаленим, емоційним і меланхолійним або агресивним і мотивуючим. Цей контраст робив жанр безмежним."}, tone:"cold", media:{src:"/story/project-return.png",alt:{en:"A developed Evelasting phonk project in FL Studio",uk:"Розвинений фонк-проєкт Evelasting у FL Studio"},layout:"project-right",opacity:.31,objectPosition:"center",parallax:24}},
 { id:"rebirth", label:{en:"The first real moment",uk:"Перший справжній момент"}, title:{en:"One evening. One unusual idea. One finished track.",uk:"Один вечір. Одна незвична ідея. Один завершений трек."}, lines:[{en:"No strategy.",uk:"Без стратегії."},{en:"No expectations.",uk:"Без очікувань."},{en:"Just music.",uk:"Лише музика."}], tone:"rebirth", oversizedWord:{en:"REBIRTH",uk:"ВІДРОДЖЕННЯ"}, media:{src:"/story/project-rebirth-new3.png",alt:{en:"The FL Studio project connected to Evelasting's rebirth",uk:"Проєкт FL Studio, пов’язаний із відродженням Evelasting"},layout:"project-wide",opacity:.32,objectPosition:"center",parallax:26}},
 { id:"silence", label:{en:"The interruption",uk:"Перерва"}, title:{en:"Then the music became quiet.",uk:"Потім музика стихла."}, description:{en:"Projects were started and abandoned. Motivation disappeared near the finish line. Around ten ideas were left behind, and only three survived.",uk:"Проєкти починалися й залишалися незавершеними. Мотивація зникала біля самої фінішної прямої. Приблизно десять ідей залишилися позаду, і лише три вижили."}, lines:[{en:"There were moments when starting again under a different name felt easier.",uk:"Іноді здавалося, що легше почати знову під іншим ім’ям."},{en:"But the channel had already become a part of me.",uk:"Але канал уже став частиною мене."}], tone:"silence", oversizedWord:{en:"SILENCE",uk:"ТИША"}},
 { id:"return", label:{en:"Now",uk:"Зараз"}, title:{en:"The reason to return was always there.",uk:"Причина повернутися була завжди."}, description:{en:"Not to chase artificial numbers. Not to follow every trend. But to return to something that once brought real excitement, pride and the feeling of creating something meaningful.",uk:"Не заради штучних цифр. Не щоб гнатися за кожним трендом. А щоб повернутися до того, що колись давало справжнє захоплення, гордість і відчуття створення чогось важливого."}, lines:[{en:"The story was never finished.",uk:"Історія ніколи не була завершена."},{en:"It was only waiting to continue.",uk:"Вона лише чекала на продовження."}], tone:"return", oversizedWord:{en:"RETURN",uk:"ПОВЕРНЕННЯ"}, media:{src:"/story/portrait-red-new3.jpg",alt:{en:"Evelasting illuminated by red light",uk:"Evelasting у червоному світлі"},layout:"portrait-right",opacity:.4,objectPosition:"center",parallax:18}}
];
